[workspace]

members = [
    "net-all-in-one",
    "net-config",
    "net-core",
    "net-agent",
    "net-hub",
    "net-translator",
    "net-timescale"
]

[workspace.dependencies]
log = "0.4.17"
env_logger = "0.10.0"
threadpool = "1.8.1"