[package]
name = "net-all-in-one"
version = "0.1.0"
edition = "2021"

[dependencies]
net-core = { path = "../net-core" }

log = "0.4"
quote = "1.0.23"
syn = { version = "1.0.109", features = ["parsing", "full", "visit"] }
toml = "0.7.2"
walkdir = "2.3.2"
