[package]
name = "net-timescale-api"
version = "0.1.0"
edition = "2021"


[dependencies]
net-core = { path = "../net-core" }

capnp = "0.16.1"
capnpc = "0.16.4"

[build-dependencies]
net-core = { path = "../net-core" }

[build-dependencies.capnpc]
capnpc = "0.16.4"