[package]
name = "net-timescale-api"
version = "0.1.0"
edition = "2021"


[dependencies]
net-proto-api = { path = "../net-proto-api" }

ion-rs = "0.18.1"
ion-schema = "0.7.0"

[features]
ion-text = []
ion-binary = []
ion-schema-validation = []

default = ["ion-text"]