[connection_url]
url = "postgres://postgres:PsWDgxZb@localhost/?sslmode=require&sslcert=net-timescale/src/.ssl/client.crt&sslkey=net-timescale/src/.ssl/client.key"

[max_connection_size]
size = "10"

[timescale_endpoint]
addr = "tcp://0.0.0.0:5558"

[translator_connector]
addr = "tcp://0.0.0.0:5557"