[connection_string]
url = "postgres://postgres:PsWDgxZb@localhost/?sslmode=require&sslcert=/.ssl/client.crt&sslkey=/.ssl/client.key"

[max_connection_size]
size = "10"

[timescale_router]
addr = "tcp://0.0.0.0:5558"

[translator_connector]
addr = "tcp://0.0.0.0:5557"