[package]
name = "net-timescale"
version = "0.1.0"
edition = "2021"

[dependencies]
net-core = { path = "../net-core" }

log = { workspace = true }
env_logger = { workspace = true }
threadpool = { workspace = true }

chrono = "0.4.23"
postgres = { version = "0.19.4", features = ["with-chrono-0_4", "with-serde_json-1"] }
serde_json = "1.0.91"

[dev-dependencies]
mockall = "0.11.2"
