[package]
name = "net-timescale"
version = "0.1.0"
edition = "2021"

[dependencies]
net-core = { path = "../net-core" }
net-timescale-api = { path = "../net-timescale-api" }

log = { workspace = true }
env_logger = { workspace = true }
threadpool = { workspace = true }

chrono = "0.4.23"
postgres = { version = "0.19.4", features = ["with-chrono-0_4", "with-serde_json-1"] }
serde_json = "1.0.91"
r2d2 = "0.8.10"
r2d2_postgres = "0.18.1"
elephantry = "3.2.0"
capnp = "0.16.1"
capnpc = "0.16.3"
bincode = "1.3.3"
serde_with = { version = "2.3.2", features = ["chrono"] }
serde = "1.0.159"
nng = "1.0.1"

[dev-dependencies]
mockall = "0.11.2"
