name: Build project

permissions: read-all

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install cargo check tools
        run: |
          cargo install --locked cargo-deny || true
          cargo install --locked cargo-outdated || true
          cargo install --locked cargo-udeps || true
          cargo install --locked cargo-audit || true
          cargo install --locked cargo-pants || true      

      - name: Update platform
        run: |
          sudo apt-get update

      - name: Clippy check
        run: cargo clippy --all-features -- -D warnings
          
      - name: Build and Test
        env:
          CARGO_MANIFEST_DIR: ${{ github.workspace }}
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.OWNER }}:${{ secrets.OWNER_PAT }}@github.com" > ~/.git-credentials
          touch ~/.cargo/config
          echo "[net]" > ~/.cargo/config
          echo "git-fetch-with-cli = true" >> ~/.cargo/config
          cargo test