name: Build and Push docker image to Container Registry

on:
  #  push:
  #     branches: [ "*" ]
  #   pull_request:
  #     branches: [ "*" ]
  workflow_dispatch:
    inputs:
      image_name:
        default: "net-hub"
        description: "Image name"
      image:
        default: "net-hub"
        description: "Image"
      owner:
        default: "net-stalker"
        description: "owner"
      repo:
        default: "net-monitor"
        description: "repo"
      tag:
        default: "0.0.1"
        description: "tag"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run shell script
        run: |
          echo "image_name ${{ inputs.image_name }}"
          echo "image ${{ inputs.image }}"
          echo "owner ${{ inputs.owner }}"
          echo "repo ${{ inputs.repo }}"
          echo "tag ${{ inputs.tag }}"
          sh ${GITHUB_WORKSPACE}/.github/scripts/docker_img_push.sh \
          -im ${{ inputs.image_name }} \
          -i ${{ inputs.image }} \
          -o ${{ inputs.owner }} \
          -r ${{ inputs.repo }} \
          -t ${{ inputs.tag }} \
          -u ${{ secrets.GITHUB_USERNAME }} \
          -p ${{ secrets.GITHUB_TOKEN }}
