name: Build and upload binaries to release

on:
  push:
    tags: 'v*'
    branches: [ "develop" ]

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: monitor
            asset_name: monitor-linux-amd64
            run: sudo apt-get update && sudo apt-get install libpcap-dev libzmq3-dev
            bundle: deb
            bundle_artifact_name: monitor_1.0.0_amd_64
            bundle_asset_name: monitor-macos-amd64.deb
          - os: macos-latest
            artifact_name: monitor
            asset_name: monitor-macos-amd64
            run: brew install libpcap zeromq
            bundle: osx
            bundle_artifact_name: ExampleApplication.app
            bundle_asset_name: monitor-macos-amd64.app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update platform
        run:  ${{ matrix.run }}
      - name: Build project
        run: cargo build --release
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
      - name: Create bundle
        run: cargo bundle --format=${{ matrix.bundle }}
      - name: Upload bundle
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/bundle/${{ matrix.bundle }}/${{ matrix.bundle_artifact_name }}
          asset_name: ${{ matrix.asset_name }}    
