name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean
      run: cargo clean
    - name: Update platform
      run: sudo apt-get update && sudo apt-get install libzmq-dev
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
