name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2

      - name: Update platform
        run: |
          sudo apt-get update
          sudo apt-get install libpcap-dev libzmq3-dev build-essential cmake
      - name: Build and Install NNG
        run: |
          git clone https://github.com/nanomsg/nng.git
          cd nng
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
      - name: Clean
        run: cargo clean
      - name: Build
        run: cargo build
      - name: Run tests
        env:
          CARGO_MANIFEST_DIR: ${{ github.workspace }}
        run: |
          echo "CARGO_MANIFEST_DIR is: $CARGO_MANIFEST_DIR"
          cargo test
